# Generated by Django 4.1.6 on 2024-05-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
    ]
