# Generated by Django 4.1.6 on 2024-06-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
