# Generated by Django 4.1.6 on 2024-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='photo',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
