# Generated by Django 4.1.6 on 2024-06-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_trips_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trips',
        ),
    ]
